//  We have given a string and we want to print all the subset generated by the string 


#include<bits/stdc++.h>
using namespace std;

void printStr(string s, string out, int idx){
    if(idx == s.size()) {
        cout<< out <<" ";
        return;
    }

    char curr = s[idx];

    // exclude current char
    printStr(s, out, idx+1);

    out.push_back(curr);

    // include current char
    printStr(s,out, idx+1);

}

int main(){
    string s; cin>>s;

    string ans ="";
    printStr(s, ans, 0);
    return 0;
}